server:
  port: ${port:0}

spring:
  application:
    name: ms-oauth
  cloud:
    gateway:
     discovery:
        locator:
          enabled: true
          lower-case-service-id: true
     routes:
      - id: ms-worker
        uri: http://localhost:8761/eureka
        predicates:
        - Path=/ms-worker/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
          
