eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
server:
  port: 8100
spring:
  application:
    name: ms-kafka-consumer
  kafka:
    producer:
      bootstrap-servers: localhost:29092
